### ISSUE TITLE
Add offline JavaScript tutorial

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/intro#49]
Since #45 we have a JavaScript tutorial which can be used offline.
Please follow the documentation in the _docs folder to add this tutorial to the offline branch and make it available without internet connection.

- [x] add offline link to JavaScript tutorial #58 
- [x] add index page which redirects #56 
- [x] add tutorial content to the offline branch, see [documentation](https://github.com/CoderDojoPotsdam/intro/tree/master/_docs#how-to-add-offline-content) #60 
- [x] point to offline content in [index file](https://github.com/CoderDojoPotsdam/intro/blob/offline/js-beginners/index.html)

Hints:
- https://github.com/CoderDojoPotsdam/intro/blob/master/_data/tutorials.yml#L172 - the offline tutorial

**Comment by niccokunzmann** [comment]
@Codarus, Thanks for your pul request!

To your questions: You can find the source here: https://github.com/OpenTechSchool/js-beginners-1/

Whenever you have http://ORGANIZATION.github.io/REPO, you can find the repository at github.com/ORGANIZATION/REPO It took me years to realize this.

In order to make it available via an offline link, the tutorials.yml must be modified. You can have a look at the docs: https://github.com/CoderDojoPotsdam/intro/tree/master/_docs#how-to-add-offline-content-to-a-tutorial
and improve them in the process. If you have any questions, let us know :)

**Comment by Codarus** [comment]
Hi @niccokunzmann,

The tutorials.yml has been modified.

**Comment by niccokunzmann** [comment]
@Codarus Thanks! I merged and edited the issue description https://github.com/CoderDojoPotsdam/intro/issues/49#issue-264151485 to include all which was done and needs to be done to close the issue.

**Comment by Codarus** [comment]
@niccokunzmann  I reread the _docs and looked at some of the other folders and realized what was missing. I've since added the tutorials to the offline folder.

**Comment by niccokunzmann** [comment]
I think, the only thing missing ot close this is to have the [index file](https://github.com/CoderDojoPotsdam/intro/blob/offline/js-beginners/index.html) point to the offline content.

**Comment by niccokunzmann** [comment]
closed by #64.
